### PR TITLE
Add riff buildtemplate

### PR DESCRIPTION
**Pull request by scothis**
Build image with `ko` https://github.com/google/go-containerregistry/blob/master/cmd/ko/README.md

### CODE REVIEW

**Comment by scothis** [comment]
Need to setup yaml and image uploads before merging.

**Comment by scothis** [comment]
The actual publish script will only run from master (after this PR is merged)

**Comment by trisberg** [comment]
why is the build taking so long? `In progress — started 2 hours ago`

**Comment by scothis** [comment]
I turned off the travis-ci.com integration while it was running since builds were duplicated with travis-ci.org. That particular job will never finish.

**Pull request merged**
